#!/usr/bin/env python
import argparse
import boto3
import logging

from new_sub_account.new_sub_account import AccountCreator
from setup_sso.setup_sso import AccountSetup
from typing import Optional
from vpc_cleaner.vpc_cleaner import VPCCleaner, AccountCleaner

_LOG_LEVEL_STRINGS = {
    'CRITICAL': logging.CRITICAL,
    'ERROR': logging.ERROR,
    'WARNING': logging.WARNING,
    'INFO': logging.INFO,
    'DEBUG': logging.DEBUG
}

def main(
        account_name: str,
        ivy_tag: str,
        saml_provider: str,
        saml_file: str,
        log_level: str = 'INFO',
        email: Optional[str] = None
    ) -> None:
    # Setup logging facility
    logging.basicConfig(format="%(asctime)s %(levelname)s (%(threadName)s) [%(name)s] %(message)s")
    log = logging.getLogger()  # Gets the root logger
    log.setLevel(_LOG_LEVEL_STRINGS[log_level])

    aws_partition = boto3.client('ec2').meta.partition
    if email:
        log.info("I will try to create sub-account %s", account_name)
        # Create sub account
        account = AccountCreator(aws_partition=aws_partition)
        account.create(email, account_name)
        sub_account_role_arn = f"arn:{aws_partition}:iam::{account.account_id}:role/OrganizationAccountAccessRole"
        assume_role = boto3.client('sts').assume_role(
            RoleArn=sub_account_role_arn,
            RoleSessionName='IvyAccountTools'
        )
        sub_account_session = Session(
            aws_access_key_id=assume_role['Credentials']['AccessKeyId'],
            aws_secret_access_key=assume_role['Credentials']['SecretAccessKey'],
            aws_session_token=assume_role['Credentials']['SessionToken']
        )
        sub_account_iam = sub_account_session.client('iam')
    else:
        log.info("No E-Mail was provided so I will not create a sub-account")
        sub_account_session = None
        sub_account_iam = None

    # Setup AWS alias and roles
    setup_sso = AccountSetup(client=sub_account_iam)
    setup_sso.alias(account_name)
    saml_name = ivy_tag + '-' + saml_provider
    saml_path = Path(saml_file)
    setup_sso.saml(saml_name, saml_path)
    setup_sso.create_default_roles()

    # Clean vpcs in all regions
    cleaner = AccountCleaner(dry_run=False, session=sub_account_session)
    cleaner.clean_all_vpcs_in_all_regions()

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="""
        1. Creates new sub-account, if email is provided
        2. Removes default VPCs
        3. Sets account alias
        4. Configures SAML
        5. Creates default roles and allows access via SAML only
        """
    )
    parser.add_argument(
        "-a", "--account-name",
        type=str,
        required=True,
        help="AWS Account Name and alias"
    )
    parser.add_argument(
        "-f", "--saml-metadata-document-file",
        type=str,
        dest="saml_file",
        required=True,
        help="Path to An XML document generated by an identity provider (IdP) that supports SAML 2.0"
    )
    parser.add_argument(
        "-s", "--saml-provider-name",
        type=str,
        default='gsuite',
        dest="saml_provider",
        help="Name of the saml provider. Examples: gsuite, msft"
    )
    parser.add_argument(
        "-e", "--e-mail",
        type=str,
        default=None,
        dest="email",
        help="E-Mail address for the AWS Sub Account"
    )
    parser.add_argument(
        "-t", "--ivy-tag",
        type=str,
        default="ivy",
        help="Ivy tag also known as namespace"
    )
    parser.add_argument(
        "-l", "--log-level",
        type=str,
        default='INFO',
        choices=_LOG_LEVEL_STRINGS.keys(),
        help="Set the logging output level"
    )
    args = parser.parse_args()
    main(
        args.account_name,
        args.ivy_tag,
        args.saml_provider,
        args.saml_file,
        args.log_level,
        args.email
    )
